-- -----------------------------------------------------
-- Table `cartify_ecommerce`.`country`
-- -----------------------------------------------------
--CREATE TABLE country (
-- id smallint unsigned NOT NULL,
-- code varchar(2) DEFAULT NULL,
-- name varchar(255) DEFAULT NULL,
-- PRIMARY KEY (id)
--) ENGINE=InnoDB;

-- Postgres
CREATE TABLE IF NOT EXISTS "cartify_ecommerce".country (
id SMALLINT NOT NULL,
code varchar(2) DEFAULT NULL,
name varchar(255) DEFAULT null,
CONSTRAINT "country_pk" PRIMARY KEY (id ASC)
) ;

-- -----------------------------------------------------
-- Table `cartify_ecommerce`.`state`
-- -----------------------------------------------------
--CREATE TABLE state (
-- id smallint unsigned NOT NULL AUTO_INCREMENT,
-- name varchar(255) DEFAULT NULL,
-- country_id smallint unsigned NOT NULL,
-- PRIMARY KEY (id),
-- KEY fk_country (country_id),
-- CONSTRAINT fk_country FOREIGN KEY (country_id) REFERENCES country (id)
--) ENGINE=InnoDB AUTO_INCREMENT=1;

-- Postgres
CREATE TABLE IF NOT EXISTS "cartify_ecommerce".state (
  id smallint not null PRIMARY KEY,
  name varchar(255) DEFAULT NULL,
  country_id smallint NOT NULL,
  CONSTRAINT fk_country FOREIGN KEY (country_id) REFERENCES "cartify_ecommerce".country (id)
) ;

-- -----------------------------------------------------
-- View Data
-- -----------------------------------------------------
select * from cartify_ecommerce.state s ; -- API= http://localhost:8080/api/states
select * from cartify_ecommerce.country c ; -- API= http://localhost:8080/api/countries

-- State of certain country : http://localhost:8080/api/states/search/findByCountryCode?code=IN

-- -----------------------------------------------------
-- INSERT country
-- -----------------------------------------------------
INSERT INTO cartify_ecommerce.country (id, code, "name") VALUES 
(nextval('cartify_ecommerce.country_seq'),'BR','Brazil'),
(nextval('cartify_ecommerce.country_seq'),'CA','Canada'),
(nextval('cartify_ecommerce.country_seq'),'DE','Germany'),
(nextval('cartify_ecommerce.country_seq'),'IN','India'),
(nextval('cartify_ecommerce.country_seq'),'TR','Turkey'),
(nextval('cartify_ecommerce.country_seq'),'US','United States');

-- -----------------------------------------------------
-- INSERT State
-- -----------------------------------------------------
INSERT INTO cartify_ecommerce.state (id, "name", country_id) VALUES
(nextval('cartify_ecommerce.state_seq'),'Acre',1),
(nextval('cartify_ecommerce.state_seq'),'Alagoas',1),
(nextval('cartify_ecommerce.state_seq'),'Amapá',1),
(nextval('cartify_ecommerce.state_seq'),'Amazonas',1),
(nextval('cartify_ecommerce.state_seq'),'Bahia',1),
(nextval('cartify_ecommerce.state_seq'),'Ceará',1),
(nextval('cartify_ecommerce.state_seq'),'Distrito Federal',1),
(nextval('cartify_ecommerce.state_seq'),'Espírito Santo',1),
(nextval('cartify_ecommerce.state_seq'),'Goiás',1),
(nextval('cartify_ecommerce.state_seq'),'Maranhão',1),
(nextval('cartify_ecommerce.state_seq'),'Mato Grosso do Sul',1),
(nextval('cartify_ecommerce.state_seq'),'Mato Grosso',1),
(nextval('cartify_ecommerce.state_seq'),'Minas Gerais',1),
(nextval('cartify_ecommerce.state_seq'),'Paraná',1),
(nextval('cartify_ecommerce.state_seq'),'Paraíba',1),
(nextval('cartify_ecommerce.state_seq'),'Pará',1),
(nextval('cartify_ecommerce.state_seq'),'Pernambuco',1),
(nextval('cartify_ecommerce.state_seq'),'Piaui',1),
(nextval('cartify_ecommerce.state_seq'),'Rio de Janeiro',1),
(nextval('cartify_ecommerce.state_seq'),'Rio Grande do Norte',1),
(nextval('cartify_ecommerce.state_seq'),'Rio Grande do Sul',1),
(nextval('cartify_ecommerce.state_seq'),'Rondônia',1),
(nextval('cartify_ecommerce.state_seq'),'Roraima',1),
(nextval('cartify_ecommerce.state_seq'),'Santa Catarina',1),
(nextval('cartify_ecommerce.state_seq'),'Sergipe',1),
(nextval('cartify_ecommerce.state_seq'),'São Paulo',1),
(nextval('cartify_ecommerce.state_seq'),'Tocantins',1),
(nextval('cartify_ecommerce.state_seq'),'Alberta',2),
(nextval('cartify_ecommerce.state_seq'),'British Columbia',2),
(nextval('cartify_ecommerce.state_seq'),'Manitoba',2),
(nextval('cartify_ecommerce.state_seq'),'New Brunswick',2),
(nextval('cartify_ecommerce.state_seq'),'Newfoundland and Labrador',2),
(nextval('cartify_ecommerce.state_seq'),'Northwest Territories',2),
(nextval('cartify_ecommerce.state_seq'),'Nova Scotia',2),
(nextval('cartify_ecommerce.state_seq'),'Nunavut',2),
(nextval('cartify_ecommerce.state_seq'),'Ontario',2),
(nextval('cartify_ecommerce.state_seq'),'Prince Edward Island',2),
(nextval('cartify_ecommerce.state_seq'),'Quebec',2),
(nextval('cartify_ecommerce.state_seq'),'Saskatchewan',2),
(nextval('cartify_ecommerce.state_seq'),'Yukon',2),
(nextval('cartify_ecommerce.state_seq'),'Baden-Württemberg',3),
(nextval('cartify_ecommerce.state_seq'),'Bavaria',3),
(nextval('cartify_ecommerce.state_seq'),'Berlin',3),
(nextval('cartify_ecommerce.state_seq'),'Brandenburg',3),
(nextval('cartify_ecommerce.state_seq'),'Bremen',3),
(nextval('cartify_ecommerce.state_seq'),'Hamburg',3),
(nextval('cartify_ecommerce.state_seq'),'Hesse',3),
(nextval('cartify_ecommerce.state_seq'),'Lower Saxony',3),
(nextval('cartify_ecommerce.state_seq'),'Mecklenburg-Vorpommern',3),
(nextval('cartify_ecommerce.state_seq'),'North Rhine-Westphalia',3),
(nextval('cartify_ecommerce.state_seq'),'Rhineland-Palatinate',3),
(nextval('cartify_ecommerce.state_seq'),'Saarland',3),
(nextval('cartify_ecommerce.state_seq'),'Saxony',3),
(nextval('cartify_ecommerce.state_seq'),'Saxony-Anhalt',3),
(nextval('cartify_ecommerce.state_seq'),'Schleswig-Holstein',3),
(nextval('cartify_ecommerce.state_seq'),'Thuringia',3),
(nextval('cartify_ecommerce.state_seq'),'Andhra Pradesh',4),
(nextval('cartify_ecommerce.state_seq'),'Arunachal Pradesh',4),
(nextval('cartify_ecommerce.state_seq'),'Assam',4),
(nextval('cartify_ecommerce.state_seq'),'Bihar',4),
(nextval('cartify_ecommerce.state_seq'),'Chhattisgarh',4),
(nextval('cartify_ecommerce.state_seq'),'Goa',4),
(nextval('cartify_ecommerce.state_seq'),'Gujarat',4),
(nextval('cartify_ecommerce.state_seq'),'Haryana',4),
(nextval('cartify_ecommerce.state_seq'),'Himachal Pradesh',4),
(nextval('cartify_ecommerce.state_seq'),'Jammu & Kashmir',4),
(nextval('cartify_ecommerce.state_seq'),'Jharkhand',4),
(nextval('cartify_ecommerce.state_seq'),'Karnataka',4),
(nextval('cartify_ecommerce.state_seq'),'Kerala',4),
(nextval('cartify_ecommerce.state_seq'),'Madhya Pradesh',4),
(nextval('cartify_ecommerce.state_seq'),'Maharashtra',4),
(nextval('cartify_ecommerce.state_seq'),'Manipur',4),
(nextval('cartify_ecommerce.state_seq'),'Meghalaya',4),
(nextval('cartify_ecommerce.state_seq'),'Mizoram',4),
(nextval('cartify_ecommerce.state_seq'),'Nagaland',4),
(nextval('cartify_ecommerce.state_seq'),'Odisha',4),
(nextval('cartify_ecommerce.state_seq'),'Punjab',4),
(nextval('cartify_ecommerce.state_seq'),'Rajasthan',4),
(nextval('cartify_ecommerce.state_seq'),'Sikkim',4),
(nextval('cartify_ecommerce.state_seq'),'Tamil Nadu',4),
(nextval('cartify_ecommerce.state_seq'),'Telangana',4),
(nextval('cartify_ecommerce.state_seq'),'Tripura',4),
(nextval('cartify_ecommerce.state_seq'),'Uttar Pradesh',4),
(nextval('cartify_ecommerce.state_seq'),'Uttarakhand',4),
(nextval('cartify_ecommerce.state_seq'),'West Bengal',4),
(nextval('cartify_ecommerce.state_seq'),'Andaman and Nicobar Islands',4),
(nextval('cartify_ecommerce.state_seq'),'Chandigarh',4),
(nextval('cartify_ecommerce.state_seq'),'Dadra and Nagar Haveli',4),
(nextval('cartify_ecommerce.state_seq'),'Daman & Diu',4),
(nextval('cartify_ecommerce.state_seq'),'Lakshadweep',4),
(nextval('cartify_ecommerce.state_seq'),'Puducherry',4),
(nextval('cartify_ecommerce.state_seq'),'The Government of NCT of Delhi',4),
(nextval('cartify_ecommerce.state_seq'),'Alabama',6),
(nextval('cartify_ecommerce.state_seq'),'Alaska',6),
(nextval('cartify_ecommerce.state_seq'),'Arizona',6),
(nextval('cartify_ecommerce.state_seq'),'Arkansas',6),
(nextval('cartify_ecommerce.state_seq'),'California',6),
(nextval('cartify_ecommerce.state_seq'),'Colorado',6),
(nextval('cartify_ecommerce.state_seq'),'Connecticut',6),
(nextval('cartify_ecommerce.state_seq'),'Delaware',6),
(nextval('cartify_ecommerce.state_seq'),'District Of Columbia',6),
(nextval('cartify_ecommerce.state_seq'),'Florida',6),
(nextval('cartify_ecommerce.state_seq'),'Georgia',6),
(nextval('cartify_ecommerce.state_seq'),'Hawaii',6),
(nextval('cartify_ecommerce.state_seq'),'Idaho',6),
(nextval('cartify_ecommerce.state_seq'),'Illinois',6),
(nextval('cartify_ecommerce.state_seq'),'Indiana',6),
(nextval('cartify_ecommerce.state_seq'),'Iowa',6),
(nextval('cartify_ecommerce.state_seq'),'Kansas',6),
(nextval('cartify_ecommerce.state_seq'),'Kentucky',6),
(nextval('cartify_ecommerce.state_seq'),'Louisiana',6),
(nextval('cartify_ecommerce.state_seq'),'Maine',6),
(nextval('cartify_ecommerce.state_seq'),'Maryland',6),
(nextval('cartify_ecommerce.state_seq'),'Massachusetts',6),
(nextval('cartify_ecommerce.state_seq'),'Michigan',6),
(nextval('cartify_ecommerce.state_seq'),'Minnesota',6),
(nextval('cartify_ecommerce.state_seq'),'Mississippi',6),
(nextval('cartify_ecommerce.state_seq'),'Missouri',6),
(nextval('cartify_ecommerce.state_seq'),'Montana',6),
(nextval('cartify_ecommerce.state_seq'),'Nebraska',6),
(nextval('cartify_ecommerce.state_seq'),'Nevada',6),
(nextval('cartify_ecommerce.state_seq'),'New Hampshire',6),
(nextval('cartify_ecommerce.state_seq'),'New Jersey',6),
(nextval('cartify_ecommerce.state_seq'),'New Mexico',6),
(nextval('cartify_ecommerce.state_seq'),'New York',6),
(nextval('cartify_ecommerce.state_seq'),'North Carolina',6),
(nextval('cartify_ecommerce.state_seq'),'North Dakota',6),
(nextval('cartify_ecommerce.state_seq'),'Ohio',6),
(nextval('cartify_ecommerce.state_seq'),'Oklahoma',6),
(nextval('cartify_ecommerce.state_seq'),'Oregon',6),
(nextval('cartify_ecommerce.state_seq'),'Pennsylvania',6),
(nextval('cartify_ecommerce.state_seq'),'Rhode Island',6),
(nextval('cartify_ecommerce.state_seq'),'South Carolina',6),
(nextval('cartify_ecommerce.state_seq'),'South Dakota',6),
(nextval('cartify_ecommerce.state_seq'),'Tennessee',6),
(nextval('cartify_ecommerce.state_seq'),'Texas',6),
(nextval('cartify_ecommerce.state_seq'),'Utah',6),
(nextval('cartify_ecommerce.state_seq'),'Vermont',6),
(nextval('cartify_ecommerce.state_seq'),'Virginia',6),
(nextval('cartify_ecommerce.state_seq'),'Washington',6),
(nextval('cartify_ecommerce.state_seq'),'West Virginia',6),
(nextval('cartify_ecommerce.state_seq'),'Wisconsin',6),
(nextval('cartify_ecommerce.state_seq'),'Wyoming',6),
(nextval('cartify_ecommerce.state_seq'),'Adıyaman',5),
(nextval('cartify_ecommerce.state_seq'),'Afyonkarahisar',5),
(nextval('cartify_ecommerce.state_seq'),'Ağrı',5),
(nextval('cartify_ecommerce.state_seq'),'Aksaray',5),
(nextval('cartify_ecommerce.state_seq'),'Amasya',5),
(nextval('cartify_ecommerce.state_seq'),'Ankara',5),
(nextval('cartify_ecommerce.state_seq'),'Antalya',5),
(nextval('cartify_ecommerce.state_seq'),'Ardahan',5),
(nextval('cartify_ecommerce.state_seq'),'Artvin',5),
(nextval('cartify_ecommerce.state_seq'),'Aydın',5),
(nextval('cartify_ecommerce.state_seq'),'Balıkesir',5),
(nextval('cartify_ecommerce.state_seq'),'Bartın',5),
(nextval('cartify_ecommerce.state_seq'),'Batman',5),
(nextval('cartify_ecommerce.state_seq'),'Bayburt',5),
(nextval('cartify_ecommerce.state_seq'),'Bilecik',5),
(nextval('cartify_ecommerce.state_seq'),'Bingöl',5),
(nextval('cartify_ecommerce.state_seq'),'Bitlis',5),
(nextval('cartify_ecommerce.state_seq'),'Bolu',5),
(nextval('cartify_ecommerce.state_seq'),'Burdur',5),
(nextval('cartify_ecommerce.state_seq'),'Bursa',5),
(nextval('cartify_ecommerce.state_seq'),'Çanakkale',5),
(nextval('cartify_ecommerce.state_seq'),'Çankırı',5),
(nextval('cartify_ecommerce.state_seq'),'Çorum',5),
(nextval('cartify_ecommerce.state_seq'),'Denizli',5),
(nextval('cartify_ecommerce.state_seq'),'Diyarbakır',5),
(nextval('cartify_ecommerce.state_seq'),'Düzce',5),
(nextval('cartify_ecommerce.state_seq'),'Edirne',5),
(nextval('cartify_ecommerce.state_seq'),'Elazığ',5),
(nextval('cartify_ecommerce.state_seq'),'Erzincan',5),
(nextval('cartify_ecommerce.state_seq'),'Erzurum',5),
(nextval('cartify_ecommerce.state_seq'),'Eskişehir',5),
(nextval('cartify_ecommerce.state_seq'),'Gaziantep',5),
(nextval('cartify_ecommerce.state_seq'),'Giresun',5),
(nextval('cartify_ecommerce.state_seq'),'Gümüşhane',5),
(nextval('cartify_ecommerce.state_seq'),'Hakkâri',5),
(nextval('cartify_ecommerce.state_seq'),'Hatay',5),
(nextval('cartify_ecommerce.state_seq'),'Iğdır',5),
(nextval('cartify_ecommerce.state_seq'),'Isparta',5),
(nextval('cartify_ecommerce.state_seq'),'İstanbul',5),
(nextval('cartify_ecommerce.state_seq'),'İzmir',5),
(nextval('cartify_ecommerce.state_seq'),'Kahramanmaraş',5),
(nextval('cartify_ecommerce.state_seq'),'Karabük',5),
(nextval('cartify_ecommerce.state_seq'),'Karaman',5),
(nextval('cartify_ecommerce.state_seq'),'Kars',5),
(nextval('cartify_ecommerce.state_seq'),'Kastamonu',5),
(nextval('cartify_ecommerce.state_seq'),'Kayseri',5),
(nextval('cartify_ecommerce.state_seq'),'Kırıkkale',5),
(nextval('cartify_ecommerce.state_seq'),'Kırklareli',5),
(nextval('cartify_ecommerce.state_seq'),'Kırşehir',5),
(nextval('cartify_ecommerce.state_seq'),'Kilis',5),
(nextval('cartify_ecommerce.state_seq'),'Kocaeli',5),
(nextval('cartify_ecommerce.state_seq'),'Konya',5),
(nextval('cartify_ecommerce.state_seq'),'Kütahya',5),
(nextval('cartify_ecommerce.state_seq'),'Malatya',5),
(nextval('cartify_ecommerce.state_seq'),'Manisa',5),
(nextval('cartify_ecommerce.state_seq'),'Mardin',5),
(nextval('cartify_ecommerce.state_seq'),'Mersin',5),
(nextval('cartify_ecommerce.state_seq'),'Muğla',5),
(nextval('cartify_ecommerce.state_seq'),'Muş',5),
(nextval('cartify_ecommerce.state_seq'),'Nevşehir',5),
(nextval('cartify_ecommerce.state_seq'),'Niğde',5),
(nextval('cartify_ecommerce.state_seq'),'Ordu',5),
(nextval('cartify_ecommerce.state_seq'),'Osmaniye',5),
(nextval('cartify_ecommerce.state_seq'),'Rize',5),
(nextval('cartify_ecommerce.state_seq'),'Sakarya',5),
(nextval('cartify_ecommerce.state_seq'),'Samsun',5),
(nextval('cartify_ecommerce.state_seq'),'Siirt',5),
(nextval('cartify_ecommerce.state_seq'),'Sinop',5),
(nextval('cartify_ecommerce.state_seq'),'Sivas',5),
(nextval('cartify_ecommerce.state_seq'),'Şanlıurfa',5),
(nextval('cartify_ecommerce.state_seq'),'Şırnak',5),
(nextval('cartify_ecommerce.state_seq'),'Tekirdağ',5),
(nextval('cartify_ecommerce.state_seq'),'Tokat',5),
(nextval('cartify_ecommerce.state_seq'),'Trabzon',5),
(nextval('cartify_ecommerce.state_seq'),'Tunceli',5),
(nextval('cartify_ecommerce.state_seq'),'Uşak',5),
(nextval('cartify_ecommerce.state_seq'),'Van',5),
(nextval('cartify_ecommerce.state_seq'),'Yalova',5),
(nextval('cartify_ecommerce.state_seq'),'Yozgat',5),
(nextval('cartify_ecommerce.state_seq'),'Zonguldak',5);


